#!/bin/sh /etc/rc.common

USE_PROCD=1

start_service() {
        local enabled
        config_load 'm_conf'
		config_get address general 'address' ''
		config_get port general 'port' ''


	if [ "$enabled" -eq 1 ]; then
	        procd_open_instance
	        procd_set_param command /usr/bin/mqtt_program -h $address -p $port
			procd_set_param file /etc/config/m_conf
        	procd_close_instance
	fi
}

service_triggers() {
	procd_add_reload_trigger "m_conf"
}

reload_service() {
	stop
	start
}
